# Generated by Django 3.1.7 on 2021-02-27 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField(default=1)),
                ('house_size', models.CharField(max_length=50, null=True)),
                ('food_choices', models.CharField(max_length=50, null=True)),
                ('water_consumption', models.IntegerField(default=0)),
                ('water_frequency', models.IntegerField(default=1)),
                ('purchases', models.IntegerField(default=0, null=True)),
                ('waste_production', models.IntegerField(default=0)),
                ('recycle', models.TextField(choices=[('G', 'GLASS'), ('PL', 'PLASTIC'), ('P', 'PAPER'), ('A', 'ALUMINIUM'), ('S', 'STEEL'), ('FW', 'FOODWASTE'), ('N', 'NONE')], default='N')),
                ('transport_car', models.IntegerField(default=0)),
                ('transport_public', models.IntegerField(default=0)),
                ('transport_air', models.IntegerField(default=0)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
